### ISSUE TITLE
H264 TCP Decoder

### ISSUE THREAD

**Issue by Seikon** [mbullington/yellowstone#10]
In addition to improve the library we could develop a h264 video decoder from rtp-packages. This method of deccoding from rtp-packages is very commom in ip-cameras and is very difficult to find a solution for nodejs (imposible)

**Comment by mbullington** [comment]
This seems like a good idea in theory, however with performance issues of a pure JS H.264 solution, along with potential issues with licensing and royalty fees, I feel that having an H.264 decoder in yellowstone wouldn't be worth the large effort required. It would (as long as the current generation of JS technology/performance persists) always be inferior to a native solution (that could you maybe make work since this is project targeting node.js primarially), and it would always be legally dubious.

If any of this changes in the future, I'd be happy to open this issue back up, but until then I'll mark it as wontfix.

Thanks!

**Comment by RogerHardiman** [comment]
Just to add to this. Yellowstone's task is to receive RTP packets. What it should also include is the processing of the RTP packets to extract the H264 NAL Units.
(this is some very simple buffer manipulation)
Yellowstone can then emit the actual H264 data (the NALs) which could be
a) written directly into a .264 file for playing with a media player
or
b) passing into a Javascript H264 decoder like the Broadway project (a port of a H264 decoder to JS using asm.js)

**Comment by RogerHardiman** [comment]
Update to my post from yesterday.

In my fork of yellowstone I have added the capability of extracting the H264 SPS, PPS and NAL data from the stream and writing it to a .264 video file. This file can be played with ffmpeg.

This bring yellowstone up to the same level as Live555 and SharpRTSP which can dump the video into a .264 video file.

You could expand on this and feed the data (H264 SPS/PPS and NAL Units) into your own H264 decoder such as the Broadway Project which ported a H264 decoder written in C to run on Javascript with asm.js

**Comment by mbullington** [comment]
Hello!

I'll continue on the discussion in your pull request, but thank you for all of these contributions! (you may have more commits than me 😄 ).

As I've said earlier, if you'd like to do something with Broadway.js or other feel free, but I feel that should be the responsibility of the end user of the library. There's just too much of a performance gap, along with the dubious licensing issues, for including something like Broadway.js in yellowstone itself. Being able to write to an .264 file is great (and the original goal I had for the library), but for going further I'll leave this issue as wontfix.

Thanks!

**Comment by RogerHardiman** [comment]
Hi Michael.

When I wrote "you could feed NALs into broadway." I was actually suggesting to Siekon that he/she could do a mashup with yellowstone and broadway.

I've caused confusion there. Sorry about that.

For the yellowstone project I agree with the wontfix.

Roger

**Comment by Seikon** [comment]
Thank you for the suggestions! You are right with the scopes and pourposes of this library and it should be implemented by me. Finally I solved my question of implementation but I would like to Fork the repository and contribute to the library in order to develop new funcionalities.

**Comment by RogerHardiman** [comment]
Hi Seikon.
I'd be interested in seeing your contributions. I've got a fork with code to extract the H264 NALs (and the SPS and PPS) and also to add RTSP keepalive and RTCP report messages. I've also got a better implementation of onData() that copes when the data is fragmented across reads.
Roger

**Comment by Seikon** [comment]
Your contributions are very nice! Some RTP devices need keepalive messages for continuous data transmit. I think for the moment i could contribute adding new ways for classify RTP packets and add new attributes for get more information about it

**Comment by RogerHardiman** [comment]
Hi Seikon,
My own thoughts are
  Support for other RTP payloads (we have H264 - could add some Audio format, maybe MJPEG (there was a fork last year for this that I only just found) and maybe H265 (current draft RFC)
  
  UDP support and Multicast support.

  Send proper RTCP replies about the connection status instead of the empty RR reports that I send.

  Speed up my onData() code. Right now it processes a single bit at a time. In places we have a data length (Content-Length or an Interleaved RTP/RTCP packet) we could use array copies and work out the number of bytes that can be copied instead of a 'for loop'. There was another implementation on onData() in the fork that processed MJPEG packets. That one may be faster than mine.

Roger

**Comment by Tauka** [comment]
@RogerHardiman @mbullington Hello! Thank you for maintaining this project. I have a question regarding NAL units, was extracting complete NAL units implemented in yellowstone?

In my current understanding, RTP payload might contain single NAL (https://tools.ietf.org/html/rfc6184#section-5.6), multiple NAL (https://tools.ietf.org/html/rfc6184#section-5.7), or single NAL can be split between multiple RTP packets (https://tools.ietf.org/html/rfc6184#section-5.8). Does yellowstone support such kind of RTP packets?

I found this PR https://github.com/mbullington/yellowstone/pull/12 that seems to solve that, but I wanted to confirm that
